### ISSUE TITLE
Filtro de Delivery Order

### ISSUE THREAD

**Issue by wilkerwma** [eGaz/eGazWeb#17]
Filtrar as Ordens de entrega por Status:
- Todas;
- Abertas;
- Encaminhadas;
- Entregues.
Apresentar somente as ordens de entregas no intervalo do dia corrente.

**Comment by fillipefeitosa** [comment]
Corrigir o filtro para as seguintes checkbox:
* Abertas
* Encaminhadas
* Entregue
-------
Ao clicar nas 3 o usuário terá um relatório com todas as Delivery Orders
