### ISSUE TITLE
[DeliveryOrder] Relatório

### ISSUE THREAD

**Issue by fillipefeitosa** [eGaz/eGazWeb#19]
É necessário que o relatório de delivery order já traga a informação direto do banco de dados, para o
* Entregador
* Produto
* Preço 
* Status

**Comment by wilkerwma** [comment]
Entregador - Pending
Produto - OK
Preço  - OK
Status - OK

**Comment by fillipefeitosa** [comment]
@wilkerwma 
Só pra confirmar, essa issue foi finalizada certo?

**Comment by wilkerwma** [comment]
Sim, finalizamos a parte de entregador juntos.
