### ISSUE TITLE
Criação de Contas: Role Default

### ISSUE THREAD

**Issue by fillipefeitosa** [eGaz/eGazWeb#9]
Ajustar a role que é atribuída automaticamente para o usuário.
Atualmente o usuário é registrado como administrador.

**Comment by wilkerwma** [comment]
Ajustado com a adição do código:
Accounts.onCreateUser(function(options, user) {
   // Set a default role to a newly created user
   user.role = 'Convidado';
   // Returns the user object
   return user;
});
